apiVersion: v1
kind: WaveManifest
metadata:
    description: A Wave multi-agent project
    name: wave-project
project:
    language: go
    test_command: "go test -race ./..."
    lint_command: "go vet ./..."
    build_command: "go build ./..."
    source_glob: "*.go"
adapters:
    claude:
        binary: claude
        default_permissions:
            allowed_tools:
                - Read
                - Write
                - Edit
                - Bash
            deny: []
        mode: headless
        output_format: json
        project_files:
            - CLAUDE.md
            - .claude/settings.json
personas:
    auditor:
        adapter: claude
        description: Security review and quality assurance
        model: opus
        temperature: 0.1
        permissions:
            allowed_tools:
                - Read
                - Grep
                - Bash(go vet*)
                - Bash(npm audit*)
            deny:
                - Write(*)
                - Edit(*)
        system_prompt_file: .wave/personas/auditor.md
    craftsman:
        adapter: claude
        description: Code implementation and testing
        model: opus
        temperature: 0.3
        permissions:
            allowed_tools:
                - Read
                - Write
                - Edit
                - Bash
            deny:
                - Bash(rm -rf /*)
        system_prompt_file: .wave/personas/craftsman.md
    debugger:
        adapter: claude
        description: Systematic issue diagnosis and root cause analysis
        model: opus
        temperature: 0.2
        permissions:
            allowed_tools:
                - Read
                - Grep
                - Glob
                - Bash(go test*)
                - Bash(git log*)
                - Bash(git diff*)
                - Bash(git bisect*)
            deny:
                - Write(*)
                - Edit(*)
        system_prompt_file: .wave/personas/debugger.md
    navigator:
        adapter: claude
        description: Read-only codebase exploration and analysis
        model: sonnet
        temperature: 0.3
        permissions:
            allowed_tools:
                - Read
                - Glob
                - Grep
                - Bash(git log*)
                - Bash(git status*)
            deny:
                - Write(*)
                - Edit(*)
                - Bash(git commit*)
                - Bash(git push*)
        system_prompt_file: .wave/personas/navigator.md
    philosopher:
        adapter: claude
        description: Architecture design and specification
        model: opus
        temperature: 0.7
        permissions:
            allowed_tools:
                - Read
                - Write(.wave/specs/*)
            deny:
                - Bash(*)
        system_prompt_file: .wave/personas/philosopher.md
    planner:
        adapter: claude
        description: Task breakdown and project planning
        model: sonnet
        temperature: 0.3
        permissions:
            allowed_tools:
                - Read
                - Glob
                - Grep
            deny:
                - Write(*)
                - Edit(*)
                - Bash(*)
        system_prompt_file: .wave/personas/planner.md
    summarizer:
        adapter: claude
        description: Context compaction for relay handoffs
        model: sonnet
        temperature: 0.2
        permissions:
            allowed_tools:
                - Read
            deny:
                - Write(*)
                - Bash(*)
        system_prompt_file: .wave/personas/summarizer.md
    github-analyst:
        adapter: claude
        description: GitHub issue analysis and quality assessment
        model: sonnet
        temperature: 0.3
        permissions:
            allowed_tools:
                - Read
                - Bash
                - Write
        system_prompt_file: .wave/personas/github-analyst.md
    github-enhancer:
        adapter: claude
        description: GitHub issue enhancement and improvement
        model: sonnet
        temperature: 0.5
        permissions:
            allowed_tools:
                - Read
                - Write
                - Bash
            deny:
                - Bash(rm *)
        system_prompt_file: .wave/personas/github-enhancer.md
    implementer:
        adapter: claude
        description: Code execution and artifact generation for pipeline steps
        model: opus
        temperature: 0.3
        permissions:
            allowed_tools:
                - Read
                - Write
                - Edit
                - Bash
                - Glob
                - Grep
            deny:
                - Bash(rm -rf /*)
                - Bash(sudo *)
        system_prompt_file: .wave/personas/implementer.md
    reviewer:
        adapter: claude
        description: Quality review, validation, and assessment
        model: sonnet
        temperature: 0.3
        permissions:
            allowed_tools:
                - Read
                - Glob
                - Grep
                - Write(artifact.json)
                - Write(artifacts/*)
                - Bash(go test*)
                - Bash(npm test*)
            deny:
                - Write(*.go)
                - Write(*.ts)
                - Edit(*)
        system_prompt_file: .wave/personas/reviewer.md
    researcher:
        adapter: claude
        description: Web research and information synthesis
        model: sonnet
        temperature: 0.5
        permissions:
            allowed_tools:
                - Read
                - Glob
                - Grep
                - WebSearch
                - WebFetch
                - Write
            deny:
                - Edit(*)
                - Bash(*)
                - Write(*.go)
                - Write(*.ts)
                - Write(*.py)
        system_prompt_file: .wave/personas/researcher.md
    github-commenter:
        adapter: claude
        description: Post comments on GitHub issues
        model: sonnet
        temperature: 0.3
        permissions:
            allowed_tools:
                - Read
                - Write(artifact.json)
                - Write(output/*)
                - Bash(gh issue comment*)
                - Bash(gh --version)
            deny:
                - Bash(gh issue edit*)
                - Bash(gh issue close*)
                - Bash(gh pr*)
                - Edit(*)
        system_prompt_file: .wave/personas/github-commenter.md
    supervisor:
        adapter: claude
        description: Work quality and process quality evaluation
        model: opus
        temperature: 0.2
        permissions:
            allowed_tools:
                - Read
                - Glob
                - Grep
                - Bash(git *)
                - Bash(ls *)
                - Bash(find *)
                - Bash(go test*)
                - Bash(cat *)
                - Bash(wc *)
            deny:
                - Write(*)
                - Edit(*)
                - Bash(git push*)
                - Bash(git commit*)
                - Bash(rm*)
        system_prompt_file: .wave/personas/supervisor.md
    provocateur:
        adapter: claude
        description: Creative challenger for divergent thinking and complexity hunting
        model: opus
        temperature: 0.8
        permissions:
            allowed_tools:
                - Read
                - Glob
                - Grep
                - Bash(wc *)
                - Bash(git log*)
                - Bash(git diff*)
                - Bash(find*)
                - Bash(ls*)
            deny:
                - Write(*)
                - Edit(*)
                - Bash(git commit*)
                - Bash(git push*)
                - Bash(rm*)
        system_prompt_file: .wave/personas/provocateur.md
runtime:
    audit:
        log_all_file_operations: false
        log_all_tool_calls: true
        log_dir: .wave/traces/
    default_timeout_minutes: 30
    max_concurrent_workers: 5
    meta_pipeline:
        max_depth: 2
        max_total_steps: 20
        max_total_tokens: 500000
        timeout_minutes: 60
    relay:
        strategy: summarize_to_checkpoint
        token_threshold_percent: 80
    workspace_root: .wave/workspaces
skill_mounts:
    - path: .wave/skills/
